### ISSUE TITLE
-hashplain doesn't keep hex state 

### ISSUE THREAD

**Issue by PenguinKeeper7** [cyclone-github/hashgen#2]
`-hashplain` forgets original plain/doesn't re-$HEX plains that need it
```
$ echo '$HEX[613A62]' | ./hashgen.exe -m ntlm -hashplain
...
8e134a51ae2df29f33695327f91a5371:a:b
```

**Comment by cyclone-github** [comment]
Printing `hash:plaintext` when calling `-hashplain` was purposeful during dev, but I agree that having an option to print `hash:HEX` would be useful.

**Comment by PenguinKeeper7** [comment]
It was more that I wanted it to be the same as the input instead of converting it and outputting a "different" plain as what I specified, idm either solution

**Comment by cyclone-github** [comment]
Gotcha, you're referring to `-hashplain` being encoding-agnostic so that it's wordlist string-in, wordlist string-out.
```
$ echo '$HEX[70617373776f7264]' | ./hashgen.bin -m ntlm -hashplain
...
8846f7eaee8fb117ad06bdd830b7586c:$HEX[70617373776f7264]
```
```
$ echo 'password' | ./hashgen.bin -m ntlm -hashplain
...
8846f7eaee8fb117ad06bdd830b7586c:password
```

**Comment by cyclone-github** [comment]
Feature added.
`v2023-09-28.1730-hashplain; modify -hashplain flag to be encoding-agnostic`
[https://github.com/cyclone-github/hashgen/commit/415b1a1009b47d288bd718d2a34032c7bc2631b7](https://github.com/cyclone-github/hashgen/commit/415b1a1009b47d288bd718d2a34032c7bc2631b7)
