### ISSUE TITLE
feature: specify custom thread count

### ISSUE THREAD

**Issue by roycewilliams** [cyclone-github/hashgen#4]
It would be handy to be able to sometimes override the default "use all the threads" approach.

**Comment by cyclone-github** [comment]
Adding a `-t nth` thread flag would be simple do to. I am curious how this would benefit your use case?

**Comment by roycewilliams** [comment]
Cool! Multiple cases, most either the "manage it running alongside other processes" variety, or the "part of a multi-stage pipeline, so I want to only dedicate X/[core-count] processes to this step" variety.
